# -*- coding: utf-8 -*-
BASIC_PARSE_INFOS = {
    "lib_song": {
        "n_items_per_page": 25,
        "url": "http://www.xiami.com/space/lib-song/u/{uid}/page"},
    "unlib_song": {
        "n_items_per_page": 25,
        "url": "http://www.xiami.com/space/unlib-song/u/{uid}/page"},
    "lib_album": {
        "n_items_per_page": 15,
        "url": "http://www.xiami.com/space/lib-album/u/{uid}/page"},
    "lib_artist": {
        "n_items_per_page": 15,
        "url": "http://www.xiami.com/space/lib-artist/u/{uid}/page"},
    "song_weekrank": {
        "n_items_per_page": 20,
        "url": "http://www.xiami.com/space/charts/u/{uid}/c/song/t/week/page"},
    "song_totalrank": {
        "n_items_per_page": 20,
        "url": "http://www.xiami.com/space/charts/u/{uid}/c/song/t/all/page"},
    "album_weekrank": {
        "n_items_per_page": 20,
        "url": "http://www.xiami.com/space/charts/u/{uid}/c/album/t/week/page"},
    "album_totalrank": {
        "n_items_per_page": 20,
        "url": "http://www.xiami.com/space/charts/u/{uid}/c/album/t/all/page"},
    "artist_totalrank": {
        "n_items_per_page": 20,
        "url": "http://www.xiami.com/space/charts/u/{uid}/c/artist/t/all/page"},
    "artist_weekrank": {
        "n_items_per_page": 20,
        "url": "http://www.xiami.com/space/charts/u/{uid}/c/artist/t/week/page"},
    "collect": {
        "n_items_per_page": 12,
        "url": "http://www.xiami.com/space/collect/u/{uid}/order/1/p/1/page"},
    "collect_fav": {
        "n_items_per_page": 12,
        "url": "http://www.xiami.com/space/collect-fav/u/{uid}/order//page"},
    "recent_listen": {
        "n_items_per_page": 50,
        "url": "http://www.xiami.com/space/charts-recent/u/{uid}/page"},
    "followings": {
        "n_items_per_page": 12,
        "url": "http://www.xiami.com/space/following/u/{uid}/page"},
    "fans": {
        "n_items_per_page": 12,
        "url": "http://www.xiami.com/space/fans/u/{uid}/page"}
}

